<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Assets/Scripts/Core/**/*.cs" />
    <Compile Include="../Assets/Scripts/Solver/**/*.cs" />
    <Compile Include="../Assets/Scripts/Application/**/*.cs" />
  </ItemGroup>
</Project>
